//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDepartment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDepartment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDepartment", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string LblDepartment {
            get {
                return ResourceManager.GetString("LblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Department Found.
        /// </summary>
        internal static string LblNoDepartmentFound {
            get {
                return ResourceManager.GetString("LblNoDepartmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Department.
        /// </summary>
        internal static string LblTotalDepartment {
            get {
                return ResourceManager.GetString("LblTotalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDepartmentDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDepartmentDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department deleted successfully!.
        /// </summary>
        internal static string MsgDepartmentDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDepartmentDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department could not saved!.
        /// </summary>
        internal static string MsgDepartmentSaveFailed {
            get {
                return ResourceManager.GetString("MsgDepartmentSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department saved successfully!.
        /// </summary>
        internal static string MsgDepartmentSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDepartmentSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department could not updated!.
        /// </summary>
        internal static string MsgDepartmentUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDepartmentUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department updated successfully!.
        /// </summary>
        internal static string MsgDepartmentUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDepartmentUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Department name found!.
        /// </summary>
        internal static string MsgDuplicateDepartment {
            get {
                return ResourceManager.GetString("MsgDuplicateDepartment", resourceCulture);
            }
        }
    }
}
