//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEmployeeSalary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmployeeSalary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEmployeeSalary", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        internal static string LblBasicSalary {
            get {
                return ResourceManager.GetString("LblBasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string LblEmployee {
            get {
                return ResourceManager.GetString("LblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Salary.
        /// </summary>
        internal static string LblEmployeeSalary {
            get {
                return ResourceManager.GetString("LblEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPF No..
        /// </summary>
        internal static string LblGPFNo {
            get {
                return ResourceManager.GetString("LblGPFNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB No..
        /// </summary>
        internal static string LblMBNo {
            get {
                return ResourceManager.GetString("LblMBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EmployeeSalary Found.
        /// </summary>
        internal static string LblNoEmployeeSalaryFound {
            get {
                return ResourceManager.GetString("LblNoEmployeeSalaryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Account.
        /// </summary>
        internal static string LblSalaryAccount {
            get {
                return ResourceManager.GetString("LblSalaryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Scale.
        /// </summary>
        internal static string LblSalaryScale {
            get {
                return ResourceManager.GetString("LblSalaryScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Teacher.
        /// </summary>
        internal static string LblSelectEmployee {
            get {
                return ResourceManager.GetString("LblSelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total EmployeeSalary.
        /// </summary>
        internal static string LblTotalEmployeeSalary {
            get {
                return ResourceManager.GetString("LblTotalEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same EmployeeSalary name found!.
        /// </summary>
        internal static string MsgDuplicateEmployeeSalary {
            get {
                return ResourceManager.GetString("MsgDuplicateEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary can&apos;t be deleted!.
        /// </summary>
        internal static string MsgEmployeeSalaryDeleteFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeSalaryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary deleted successfully!.
        /// </summary>
        internal static string MsgEmployeeSalaryDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeSalaryDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary could not saved!.
        /// </summary>
        internal static string MsgEmployeeSalarySaveFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeSalarySaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary saved successfully!.
        /// </summary>
        internal static string MsgEmployeeSalarySaveSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeSalarySaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary tcould not updated!.
        /// </summary>
        internal static string MsgEmployeeSalaryUpdateFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeSalaryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSalary updated successfully!.
        /// </summary>
        internal static string MsgEmployeeSalaryUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeSalaryUpdateSuccessful", resourceCulture);
            }
        }
    }
}
