//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDesignation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDesignation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDesignation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string LblDepartmentName {
            get {
                return ResourceManager.GetString("LblDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string LblDesignation {
            get {
                return ResourceManager.GetString("LblDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Designation Found.
        /// </summary>
        internal static string LblNoDesignationFound {
            get {
                return ResourceManager.GetString("LblNoDesignationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Only?.
        /// </summary>
        internal static string LblSchoolOnly {
            get {
                return ResourceManager.GetString("LblSchoolOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        internal static string LblSelectDepartment {
            get {
                return ResourceManager.GetString("LblSelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Designation.
        /// </summary>
        internal static string LblTotalDesignation {
            get {
                return ResourceManager.GetString("LblTotalDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDesignationDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDesignationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation deleted successfully!.
        /// </summary>
        internal static string MsgDesignationDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDesignationDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation could not saved!.
        /// </summary>
        internal static string MsgDesignationSaveFailed {
            get {
                return ResourceManager.GetString("MsgDesignationSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation saved successfully!.
        /// </summary>
        internal static string MsgDesignationSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDesignationSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation could not updated!.
        /// </summary>
        internal static string MsgDesignationUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDesignationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation updated successfully!.
        /// </summary>
        internal static string MsgDesignationUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDesignationUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Designation name found!.
        /// </summary>
        internal static string MsgDuplicateDesignation {
            get {
                return ResourceManager.GetString("MsgDuplicateDesignation", resourceCulture);
            }
        }
    }
}
