//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDeviceSetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDeviceSetup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDeviceSetup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Setup.
        /// </summary>
        internal static string LblDeviceSetup {
            get {
                return ResourceManager.GetString("LblDeviceSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string LblDeviceSetupName {
            get {
                return ResourceManager.GetString("LblDeviceSetupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string LblDeviceType {
            get {
                return ResourceManager.GetString("LblDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        internal static string LblGate {
            get {
                return ResourceManager.GetString("LblGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string LblIPAddress {
            get {
                return ResourceManager.GetString("LblIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LblLocation {
            get {
                return ResourceManager.GetString("LblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Setup Found.
        /// </summary>
        internal static string LblNoDeviceSetupFound {
            get {
                return ResourceManager.GetString("LblNoDeviceSetupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string LblPort {
            get {
                return ResourceManager.GetString("LblPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string LblSchool {
            get {
                return ResourceManager.GetString("LblSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device Type.
        /// </summary>
        internal static string LblSelectDeviceType {
            get {
                return ResourceManager.GetString("LblSelectDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Device Setup.
        /// </summary>
        internal static string LblTotalDeviceSetup {
            get {
                return ResourceManager.GetString("LblTotalDeviceSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDeviceSetupDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDeviceSetupDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup deleted successfully!.
        /// </summary>
        internal static string MsgDeviceSetupDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceSetupDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup could not saved!.
        /// </summary>
        internal static string MsgDeviceSetupSaveFailed {
            get {
                return ResourceManager.GetString("MsgDeviceSetupSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup saved successfully!.
        /// </summary>
        internal static string MsgDeviceSetupSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceSetupSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup tcould not updated!.
        /// </summary>
        internal static string MsgDeviceSetupUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDeviceSetupUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceSetup updated successfully!.
        /// </summary>
        internal static string MsgDeviceSetupUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceSetupUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DeviceSetup name found!.
        /// </summary>
        internal static string MsgDuplicateDeviceSetup {
            get {
                return ResourceManager.GetString("MsgDuplicateDeviceSetup", resourceCulture);
            }
        }
    }
}
