//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceInstitute {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceInstitute() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceInstitute", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute.
        /// </summary>
        internal static string LblInstitute {
            get {
                return ResourceManager.GetString("LblInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Institute Found.
        /// </summary>
        internal static string LblNoInstituteFound {
            get {
                return ResourceManager.GetString("LblNoInstituteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Institute.
        /// </summary>
        internal static string LblTotalInstitute {
            get {
                return ResourceManager.GetString("LblTotalInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string LbSllInstitute {
            get {
                return ResourceManager.GetString("LbSllInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Institute name found!.
        /// </summary>
        internal static string MsgDuplicateInstitute {
            get {
                return ResourceManager.GetString("MsgDuplicateInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute can&apos;t be deleted!.
        /// </summary>
        internal static string MsgInstituteDeleteFailed {
            get {
                return ResourceManager.GetString("MsgInstituteDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute deleted successfully!.
        /// </summary>
        internal static string MsgInstituteDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgInstituteDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute could not saved!.
        /// </summary>
        internal static string MsgInstituteSaveFailed {
            get {
                return ResourceManager.GetString("MsgInstituteSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute saved successfully!.
        /// </summary>
        internal static string MsgInstituteSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgInstituteSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute could not updated!.
        /// </summary>
        internal static string MsgInstituteUpdateFailed {
            get {
                return ResourceManager.GetString("MsgInstituteUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute updated successfully!.
        /// </summary>
        internal static string MsgInstituteUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgInstituteUpdateSuccessful", resourceCulture);
            }
        }
    }
}
