//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTraining {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTraining() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceTraining", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string LblEmployee {
            get {
                return ResourceManager.GetString("LblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string LblEndDate {
            get {
                return ResourceManager.GetString("LblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string LblId {
            get {
                return ResourceManager.GetString("LblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Training Found.
        /// </summary>
        internal static string LblNoTrainingFound {
            get {
                return ResourceManager.GetString("LblNoTrainingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed By.
        /// </summary>
        internal static string LblRemovedBy {
            get {
                return ResourceManager.GetString("LblRemovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed On.
        /// </summary>
        internal static string LblRemovedOn {
            get {
                return ResourceManager.GetString("LblRemovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Teacher.
        /// </summary>
        internal static string LblSelectEmployee {
            get {
                return ResourceManager.GetString("LblSelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        internal static string LblSelectStatus {
            get {
                return ResourceManager.GetString("LblSelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Training Type.
        /// </summary>
        internal static string LblSelectTrainingType {
            get {
                return ResourceManager.GetString("LblSelectTrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string LblStartDate {
            get {
                return ResourceManager.GetString("LblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Training.
        /// </summary>
        internal static string LblTotalTraining {
            get {
                return ResourceManager.GetString("LblTotalTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string LblTraining {
            get {
                return ResourceManager.GetString("LblTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Type.
        /// </summary>
        internal static string LblTrainingType {
            get {
                return ResourceManager.GetString("LblTrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Training name found!.
        /// </summary>
        internal static string MsgDuplicateTraining {
            get {
                return ResourceManager.GetString("MsgDuplicateTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training can&apos;t be deleted!.
        /// </summary>
        internal static string MsgTrainingDeleteFailed {
            get {
                return ResourceManager.GetString("MsgTrainingDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training deleted successfully!.
        /// </summary>
        internal static string MsgTrainingDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgTrainingDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training could not saved!.
        /// </summary>
        internal static string MsgTrainingSaveFailed {
            get {
                return ResourceManager.GetString("MsgTrainingSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training saved successfully!.
        /// </summary>
        internal static string MsgTrainingSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgTrainingSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training could not updated!.
        /// </summary>
        internal static string MsgTrainingUpdateFailed {
            get {
                return ResourceManager.GetString("MsgTrainingUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training updated successfully!.
        /// </summary>
        internal static string MsgTrainingUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgTrainingUpdateSuccessful", resourceCulture);
            }
        }
    }
}
