//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDutyEntry {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDutyEntry() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDutyEntry", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LblDate {
            get {
                return ResourceManager.GetString("LblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Entry.
        /// </summary>
        internal static string LblDutyEntry {
            get {
                return ResourceManager.GetString("LblDutyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Reason.
        /// </summary>
        internal static string LblDutyReason {
            get {
                return ResourceManager.GetString("LblDutyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string LblEmployee {
            get {
                return ResourceManager.GetString("LblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string LblEndDate {
            get {
                return ResourceManager.GetString("LblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Time.
        /// </summary>
        internal static string LblInTime {
            get {
                return ResourceManager.GetString("LblInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LblLocation {
            get {
                return ResourceManager.GetString("LblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DutyEntry Found.
        /// </summary>
        internal static string LblNoDutyEntryFound {
            get {
                return ResourceManager.GetString("LblNoDutyEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Time.
        /// </summary>
        internal static string LblOutTime {
            get {
                return ResourceManager.GetString("LblOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed By.
        /// </summary>
        internal static string LblRemovedBy {
            get {
                return ResourceManager.GetString("LblRemovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed On.
        /// </summary>
        internal static string LblRemovedOn {
            get {
                return ResourceManager.GetString("LblRemovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string LblStartDate {
            get {
                return ResourceManager.GetString("LblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DutyEntry.
        /// </summary>
        internal static string LblTotalDutyEntry {
            get {
                return ResourceManager.GetString("LblTotalDutyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DutyEntry name found!.
        /// </summary>
        internal static string MsgDuplicateDutyEntry {
            get {
                return ResourceManager.GetString("MsgDuplicateDutyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDutyEntryDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDutyEntryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry deleted successfully!.
        /// </summary>
        internal static string MsgDutyEntryDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyEntryDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry could not saved!.
        /// </summary>
        internal static string MsgDutyEntrySaveFailed {
            get {
                return ResourceManager.GetString("MsgDutyEntrySaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry saved successfully!.
        /// </summary>
        internal static string MsgDutyEntrySaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyEntrySaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry tcould not updated!.
        /// </summary>
        internal static string MsgDutyEntryUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDutyEntryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyEntry updated successfully!.
        /// </summary>
        internal static string MsgDutyEntryUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyEntryUpdateSuccessful", resourceCulture);
            }
        }
    }
}
