//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLeave {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLeave() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLeave", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactDuringLeave.
        /// </summary>
        internal static string ContactDuringLeave {
            get {
                return ResourceManager.GetString("ContactDuringLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressDuringLeave.
        /// </summary>
        internal static string LblAddressDuringLeave {
            get {
                return ResourceManager.GetString("LblAddressDuringLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string LblBalance {
            get {
                return ResourceManager.GetString("LblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        internal static string LblCurrentBalance {
            get {
                return ResourceManager.GetString("LblCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LblDate {
            get {
                return ResourceManager.GetString("LblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string LblEmployee {
            get {
                return ResourceManager.GetString("LblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string LblEndDate {
            get {
                return ResourceManager.GetString("LblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded your balance. Additional days wil be unpaid Leave.
        /// </summary>
        internal static string LblExceededBalance {
            get {
                return ResourceManager.GetString("LblExceededBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string LblLeave {
            get {
                return ResourceManager.GetString("LblLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave List.
        /// </summary>
        internal static string LblLeaveList {
            get {
                return ResourceManager.GetString("LblLeaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Reason.
        /// </summary>
        internal static string LblLeaveReason {
            get {
                return ResourceManager.GetString("LblLeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string LblLeaveType {
            get {
                return ResourceManager.GetString("LblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Leave Found.
        /// </summary>
        internal static string LblNoLeaveFound {
            get {
                return ResourceManager.GetString("LblNoLeaveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Days.
        /// </summary>
        internal static string LblNoofDays {
            get {
                return ResourceManager.GetString("LblNoofDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed By.
        /// </summary>
        internal static string LblRemovedBy {
            get {
                return ResourceManager.GetString("LblRemovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed On.
        /// </summary>
        internal static string LblRemovedOn {
            get {
                return ResourceManager.GetString("LblRemovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string LblSelectLeaveType {
            get {
                return ResourceManager.GetString("LblSelectLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string LblStartDate {
            get {
                return ResourceManager.GetString("LblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leave.
        /// </summary>
        internal static string LblTotalLeave {
            get {
                return ResourceManager.GetString("LblTotalLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Leave name found!.
        /// </summary>
        internal static string MsgDuplicateLeave {
            get {
                return ResourceManager.GetString("MsgDuplicateLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave can&apos;t be deleted!.
        /// </summary>
        internal static string MsgLeaveDeleteFailed {
            get {
                return ResourceManager.GetString("MsgLeaveDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave deleted successfully!.
        /// </summary>
        internal static string MsgLeaveDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave could not saved!.
        /// </summary>
        internal static string MsgLeaveSaveFailed {
            get {
                return ResourceManager.GetString("MsgLeaveSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave saved successfully!.
        /// </summary>
        internal static string MsgLeaveSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave could not updated!.
        /// </summary>
        internal static string MsgLeaveUpdateFailed {
            get {
                return ResourceManager.GetString("MsgLeaveUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave updated successfully!.
        /// </summary>
        internal static string MsgLeaveUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveUpdateSuccessful", resourceCulture);
            }
        }
    }
}
