//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNotice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNotice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceNotice", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach File.
        /// </summary>
        internal static string LblAttachFile {
            get {
                return ResourceManager.GetString("LblAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string LblId {
            get {
                return ResourceManager.GetString("LblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notice Found.
        /// </summary>
        internal static string LblNoNoticeFound {
            get {
                return ResourceManager.GetString("LblNoNoticeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string LblNotice {
            get {
                return ResourceManager.GetString("LblNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Notice.
        /// </summary>
        internal static string LblTotalNotice {
            get {
                return ResourceManager.GetString("LblTotalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        internal static string LblValidity {
            get {
                return ResourceManager.GetString("LblValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Notice name found!.
        /// </summary>
        internal static string MsgDuplicateNotice {
            get {
                return ResourceManager.GetString("MsgDuplicateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a file upto 2 mb.
        /// </summary>
        internal static string MsgFileSize {
            get {
                return ResourceManager.GetString("MsgFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload image of type .png or .pdf file.
        /// </summary>
        internal static string MsgFileType {
            get {
                return ResourceManager.GetString("MsgFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice can&apos;t be deleted!.
        /// </summary>
        internal static string MsgNoticeDeleteFailed {
            get {
                return ResourceManager.GetString("MsgNoticeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice deleted successfully!.
        /// </summary>
        internal static string MsgNoticeDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgNoticeDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice could not saved!.
        /// </summary>
        internal static string MsgNoticeSaveFailed {
            get {
                return ResourceManager.GetString("MsgNoticeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice saved successfully!.
        /// </summary>
        internal static string MsgNoticeSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgNoticeSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice tcould not updated!.
        /// </summary>
        internal static string MsgNoticeUpdateFailed {
            get {
                return ResourceManager.GetString("MsgNoticeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice updated successfully!.
        /// </summary>
        internal static string MsgNoticeUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgNoticeUpdateSuccessful", resourceCulture);
            }
        }
    }
}
