//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceBoardorUniversity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBoardorUniversity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceBoardorUniversity", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boardor University.
        /// </summary>
        internal static string LblBoardorUniversity {
            get {
                return ResourceManager.GetString("LblBoardorUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Major.
        /// </summary>
        internal static string LblDegreeMajor {
            get {
                return ResourceManager.GetString("LblDegreeMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Title.
        /// </summary>
        internal static string LblDegreeTitle {
            get {
                return ResourceManager.GetString("LblDegreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BoardorUniversity Found.
        /// </summary>
        internal static string LblNoBoardorUniversityFound {
            get {
                return ResourceManager.GetString("LblNoBoardorUniversityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string LblResult {
            get {
                return ResourceManager.GetString("LblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string LblScale {
            get {
                return ResourceManager.GetString("LblScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BoardorUniversity.
        /// </summary>
        internal static string LblTotalBoardorUniversity {
            get {
                return ResourceManager.GetString("LblTotalBoardorUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity can&apos;t be deleted!.
        /// </summary>
        internal static string MsgBoardorUniversityDeleteFailed {
            get {
                return ResourceManager.GetString("MsgBoardorUniversityDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity deleted successfully!.
        /// </summary>
        internal static string MsgBoardorUniversityDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgBoardorUniversityDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity could not saved!.
        /// </summary>
        internal static string MsgBoardorUniversitySaveFailed {
            get {
                return ResourceManager.GetString("MsgBoardorUniversitySaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity saved successfully!.
        /// </summary>
        internal static string MsgBoardorUniversitySaveSuccessful {
            get {
                return ResourceManager.GetString("MsgBoardorUniversitySaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity could not updated!.
        /// </summary>
        internal static string MsgBoardorUniversityUpdateFailed {
            get {
                return ResourceManager.GetString("MsgBoardorUniversityUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardorUniversity updated successfully!.
        /// </summary>
        internal static string MsgBoardorUniversityUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgBoardorUniversityUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same BoardorUniversity name found!.
        /// </summary>
        internal static string MsgDuplicateBoardorUniversity {
            get {
                return ResourceManager.GetString("MsgDuplicateBoardorUniversity", resourceCulture);
            }
        }
    }
}
