//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEducationLevel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEducationLevel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEducationLevel", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        internal static string LblEducationLevel {
            get {
                return ResourceManager.GetString("LblEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Education Level Found.
        /// </summary>
        internal static string LblNoEducationLevelFound {
            get {
                return ResourceManager.GetString("LblNoEducationLevelFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Education Level.
        /// </summary>
        internal static string LblTotalEducationLevel {
            get {
                return ResourceManager.GetString("LblTotalEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same EducationLevel name found!.
        /// </summary>
        internal static string MsgDuplicateEducationLevel {
            get {
                return ResourceManager.GetString("MsgDuplicateEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel can&apos;t be deleted!.
        /// </summary>
        internal static string MsgEducationLevelDeleteFailed {
            get {
                return ResourceManager.GetString("MsgEducationLevelDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel deleted successfully!.
        /// </summary>
        internal static string MsgEducationLevelDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgEducationLevelDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel could not saved!.
        /// </summary>
        internal static string MsgEducationLevelSaveFailed {
            get {
                return ResourceManager.GetString("MsgEducationLevelSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel saved successfully!.
        /// </summary>
        internal static string MsgEducationLevelSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgEducationLevelSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel could not updated!.
        /// </summary>
        internal static string MsgEducationLevelUpdateFailed {
            get {
                return ResourceManager.GetString("MsgEducationLevelUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationLevel updated successfully!.
        /// </summary>
        internal static string MsgEducationLevelUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgEducationLevelUpdateSuccessful", resourceCulture);
            }
        }
    }
}
