//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEmployeeAttendance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmployeeAttendance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEmployeeAttendance", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string LblAttendanceRemark {
            get {
                return ResourceManager.GetString("LblAttendanceRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LblDate {
            get {
                return ResourceManager.GetString("LblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string LblEmployee {
            get {
                return ResourceManager.GetString("LblEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance.
        /// </summary>
        internal static string LblEmployeeAttendance {
            get {
                return ResourceManager.GetString("LblEmployeeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EmployeeAttendance Found.
        /// </summary>
        internal static string LblNoEmployeeAttendanceFound {
            get {
                return ResourceManager.GetString("LblNoEmployeeAttendanceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string LblNote {
            get {
                return ResourceManager.GetString("LblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LblTime {
            get {
                return ResourceManager.GetString("LblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total EmployeeAttendance.
        /// </summary>
        internal static string LblTotalEmployeeAttendance {
            get {
                return ResourceManager.GetString("LblTotalEmployeeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LblType {
            get {
                return ResourceManager.GetString("LblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same EmployeeAttendance name found!.
        /// </summary>
        internal static string MsgDuplicateEmployeeAttendance {
            get {
                return ResourceManager.GetString("MsgDuplicateEmployeeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance can&apos;t be deleted!.
        /// </summary>
        internal static string MsgEmployeeAttendanceDeleteFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance deleted successfully!.
        /// </summary>
        internal static string MsgEmployeeAttendanceDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance could not saved!.
        /// </summary>
        internal static string MsgEmployeeAttendanceSaveFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance saved successfully!.
        /// </summary>
        internal static string MsgEmployeeAttendanceSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance tcould not updated!.
        /// </summary>
        internal static string MsgEmployeeAttendanceUpdateFailed {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAttendance updated successfully!.
        /// </summary>
        internal static string MsgEmployeeAttendanceUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgEmployeeAttendanceUpdateSuccessful", resourceCulture);
            }
        }
    }
}
