//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDutyReason {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDutyReason() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDutyReason", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Reason.
        /// </summary>
        internal static string LblDutyReason {
            get {
                return ResourceManager.GetString("LblDutyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Duty Reason Found.
        /// </summary>
        internal static string LblNoDutyReasonFound {
            get {
                return ResourceManager.GetString("LblNoDutyReasonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duty Reason.
        /// </summary>
        internal static string LblTotalDutyReason {
            get {
                return ResourceManager.GetString("LblTotalDutyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DutyReason name found!.
        /// </summary>
        internal static string MsgDuplicateDutyReason {
            get {
                return ResourceManager.GetString("MsgDuplicateDutyReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDutyReasonDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDutyReasonDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason deleted successfully!.
        /// </summary>
        internal static string MsgDutyReasonDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyReasonDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason could not saved!.
        /// </summary>
        internal static string MsgDutyReasonSaveFailed {
            get {
                return ResourceManager.GetString("MsgDutyReasonSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason saved successfully!.
        /// </summary>
        internal static string MsgDutyReasonSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyReasonSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason could not updated!.
        /// </summary>
        internal static string MsgDutyReasonUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDutyReasonUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyReason updated successfully!.
        /// </summary>
        internal static string MsgDutyReasonUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyReasonUpdateSuccessful", resourceCulture);
            }
        }
    }
}
