//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAccademicYear {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAccademicYear() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceAccademicYear", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year.
        /// </summary>
        internal static string LblAccademicYear {
            get {
                return ResourceManager.GetString("LblAccademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Weekend.
        /// </summary>
        internal static string LblAccadeWeekend1 {
            get {
                return ResourceManager.GetString("LblAccadeWeekend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Weekend.
        /// </summary>
        internal static string LblAccadeWeekend2 {
            get {
                return ResourceManager.GetString("LblAccadeWeekend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AccademicYear Found.
        /// </summary>
        internal static string LblNoAccademicYearFound {
            get {
                return ResourceManager.GetString("LblNoAccademicYearFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accademic Year.
        /// </summary>
        internal static string LblTotalAccademicYear {
            get {
                return ResourceManager.GetString("LblTotalAccademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year can&apos;t be deleted!.
        /// </summary>
        internal static string MsgAccademicYearDeleteFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year deleted successfully!.
        /// </summary>
        internal static string MsgAccademicYearDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year could not saved!.
        /// </summary>
        internal static string MsgAccademicYearSaveFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year saved successfully!.
        /// </summary>
        internal static string MsgAccademicYearSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year could not updated!.
        /// </summary>
        internal static string MsgAccademicYearUpdateFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccademicYear updated successfully!.
        /// </summary>
        internal static string MsgAccademicYearUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Accademic Year name found!.
        /// </summary>
        internal static string MsgDuplicateAccademicYear {
            get {
                return ResourceManager.GetString("MsgDuplicateAccademicYear", resourceCulture);
            }
        }
    }
}
