//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUpazila {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUpazila() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceUpazila", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Upazila Found.
        /// </summary>
        internal static string LblNoUpazilaFound {
            get {
                return ResourceManager.GetString("LblNoUpazilaFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Upazila.
        /// </summary>
        internal static string LblTotalUpazila {
            get {
                return ResourceManager.GetString("LblTotalUpazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila.
        /// </summary>
        internal static string LblUpazila {
            get {
                return ResourceManager.GetString("LblUpazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Upazila name found!.
        /// </summary>
        internal static string MsgDuplicateUpazila {
            get {
                return ResourceManager.GetString("MsgDuplicateUpazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila can&apos;t be deleted!.
        /// </summary>
        internal static string MsgUpazilaDeleteFailed {
            get {
                return ResourceManager.GetString("MsgUpazilaDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila deleted successfully!.
        /// </summary>
        internal static string MsgUpazilaDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgUpazilaDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila could not saved!.
        /// </summary>
        internal static string MsgUpazilaSaveFailed {
            get {
                return ResourceManager.GetString("MsgUpazilaSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila saved successfully!.
        /// </summary>
        internal static string MsgUpazilaSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgUpazilaSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila tcould not updated!.
        /// </summary>
        internal static string MsgUpazilaUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpazilaUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila updated successfully!.
        /// </summary>
        internal static string MsgUpazilaUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgUpazilaUpdateSuccessful", resourceCulture);
            }
        }
    }
}
