//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDutyShiftMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDutyShiftMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDutyShiftMaster", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift Master.
        /// </summary>
        internal static string LblDutyShiftMaster {
            get {
                return ResourceManager.GetString("LblDutyShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Duty Shift Master Found.
        /// </summary>
        internal static string LblNoDutyShiftMasterFound {
            get {
                return ResourceManager.GetString("LblNoDutyShiftMasterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duty Shift Master.
        /// </summary>
        internal static string LblTotalDutyShiftMaster {
            get {
                return ResourceManager.GetString("LblTotalDutyShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DutyShiftMaster name found!.
        /// </summary>
        internal static string MsgDuplicateDutyShiftMaster {
            get {
                return ResourceManager.GetString("MsgDuplicateDutyShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDutyShiftMasterDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster deleted successfully!.
        /// </summary>
        internal static string MsgDutyShiftMasterDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster could not saved!.
        /// </summary>
        internal static string MsgDutyShiftMasterSaveFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster saved successfully!.
        /// </summary>
        internal static string MsgDutyShiftMasterSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster could not updated!.
        /// </summary>
        internal static string MsgDutyShiftMasterUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DutyShiftMaster updated successfully!.
        /// </summary>
        internal static string MsgDutyShiftMasterUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftMasterUpdateSuccessful", resourceCulture);
            }
        }
    }
}
