//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceUser", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string LblFullName {
            get {
                return ResourceManager.GetString("LblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string LblIsActive {
            get {
                return ResourceManager.GetString("LblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string LblLoginName {
            get {
                return ResourceManager.GetString("LblLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Found.
        /// </summary>
        internal static string LblNoUserFound {
            get {
                return ResourceManager.GetString("LblNoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be atleast 8 characters long and should contain one number,one character.
        /// </summary>
        internal static string LblPattern {
            get {
                return ResourceManager.GetString("LblPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string LblRole {
            get {
                return ResourceManager.GetString("LblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        internal static string LblSelectEmployee {
            get {
                return ResourceManager.GetString("LblSelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        internal static string LblSelectRole {
            get {
                return ResourceManager.GetString("LblSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LblUser {
            get {
                return ResourceManager.GetString("LblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        internal static string LblUserList {
            get {
                return ResourceManager.GetString("LblUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string LblUserName {
            get {
                return ResourceManager.GetString("LblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission.
        /// </summary>
        internal static string LblUserPermission {
            get {
                return ResourceManager.GetString("LblUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Training name found!.
        /// </summary>
        internal static string MsgDuplicateTraining {
            get {
                return ResourceManager.GetString("MsgDuplicateTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can&apos;t be deleted!.
        /// </summary>
        internal static string MsgTrainingDeleteFailed {
            get {
                return ResourceManager.GetString("MsgTrainingDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully!.
        /// </summary>
        internal static string MsgUserDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgUserDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User could not saved!.
        /// </summary>
        internal static string MsgUserSaveFailed {
            get {
                return ResourceManager.GetString("MsgUserSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully!.
        /// </summary>
        internal static string MsgUserSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgUserSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User could not updated!.
        /// </summary>
        internal static string MsgUserUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUserUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully!.
        /// </summary>
        internal static string MsgUserUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgUserUpdateSuccessful", resourceCulture);
            }
        }
    }
}
