//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDeviceType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDeviceType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDeviceType", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string LblDeviceType {
            get {
                return ResourceManager.GetString("LblDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Device Type Found.
        /// </summary>
        internal static string LblNoDeviceTypeFound {
            get {
                return ResourceManager.GetString("LblNoDeviceTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Device Type.
        /// </summary>
        internal static string LblTotalDeviceType {
            get {
                return ResourceManager.GetString("LblTotalDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDeviceTypeDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDeviceTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType deleted successfully!.
        /// </summary>
        internal static string MsgDeviceTypeDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceTypeDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType could not saved!.
        /// </summary>
        internal static string MsgDeviceTypeSaveFailed {
            get {
                return ResourceManager.GetString("MsgDeviceTypeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType saved successfully!.
        /// </summary>
        internal static string MsgDeviceTypeSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceTypeSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType could not updated!.
        /// </summary>
        internal static string MsgDeviceTypeUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDeviceTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType updated successfully!.
        /// </summary>
        internal static string MsgDeviceTypeUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDeviceTypeUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DeviceType name found!.
        /// </summary>
        internal static string MsgDuplicateDeviceType {
            get {
                return ResourceManager.GetString("MsgDuplicateDeviceType", resourceCulture);
            }
        }
    }
}
