//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAccademicYearDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAccademicYearDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceAccademicYearDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year.
        /// </summary>
        internal static string LblAccademicYear {
            get {
                return ResourceManager.GetString("LblAccademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail.
        /// </summary>
        internal static string LblAccademicYearDetail {
            get {
                return ResourceManager.GetString("LblAccademicYearDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Date.
        /// </summary>
        internal static string LblDayDate {
            get {
                return ResourceManager.GetString("LblDayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Description.
        /// </summary>
        internal static string LblDayDescription {
            get {
                return ResourceManager.GetString("LblDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type.
        /// </summary>
        internal static string LblDayType {
            get {
                return ResourceManager.GetString("LblDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type Name.
        /// </summary>
        internal static string LblDayTypeName {
            get {
                return ResourceManager.GetString("LblDayTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Accademic Year Detail Found.
        /// </summary>
        internal static string LblNoAccademicYearDetailFound {
            get {
                return ResourceManager.GetString("LblNoAccademicYearDetailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Day Type.
        /// </summary>
        internal static string LblSelectDayType {
            get {
                return ResourceManager.GetString("LblSelectDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AccademicYear Detail.
        /// </summary>
        internal static string LblTotalAccademicYearDetail {
            get {
                return ResourceManager.GetString("LblTotalAccademicYearDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail can&apos;t be deleted!.
        /// </summary>
        internal static string MsgAccademicYearDetailDeleteFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail deleted successfully!.
        /// </summary>
        internal static string MsgAccademicYearDetailDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail could not saved!.
        /// </summary>
        internal static string MsgAccademicYearDetailSaveFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail saved successfully!.
        /// </summary>
        internal static string MsgAccademicYearDetailSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail could not updated!.
        /// </summary>
        internal static string MsgAccademicYearDetailUpdateFailed {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accademic Year Detail updated successfully!.
        /// </summary>
        internal static string MsgAccademicYearDetailUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgAccademicYearDetailUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Accademic Year Detail found!.
        /// </summary>
        internal static string MsgDuplicateAccademicYearDetail {
            get {
                return ResourceManager.GetString("MsgDuplicateAccademicYearDetail", resourceCulture);
            }
        }
    }
}
