//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDayType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDayType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDayType", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type.
        /// </summary>
        internal static string LblDayType {
            get {
                return ResourceManager.GetString("LblDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Day Type Found.
        /// </summary>
        internal static string LblNoDayTypeFound {
            get {
                return ResourceManager.GetString("LblNoDayTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Day Type.
        /// </summary>
        internal static string LblTotalDayType {
            get {
                return ResourceManager.GetString("LblTotalDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDayTypeDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDayTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Typer deleted successfully!.
        /// </summary>
        internal static string MsgDayTypeDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDayTypeDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type could not saved!.
        /// </summary>
        internal static string MsgDayTypeSaveFailed {
            get {
                return ResourceManager.GetString("MsgDayTypeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type saved successfully!.
        /// </summary>
        internal static string MsgDayTypeSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDayTypeSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type could not updated!.
        /// </summary>
        internal static string MsgDayTypeUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDayTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Type updated successfully!.
        /// </summary>
        internal static string MsgDayTypeUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDayTypeUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same DayT ype name found!.
        /// </summary>
        internal static string MsgDuplicateDayType {
            get {
                return ResourceManager.GetString("MsgDuplicateDayType", resourceCulture);
            }
        }
    }
}
