//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDivision {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDivision() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDivision", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string LblDivision {
            get {
                return ResourceManager.GetString("LblDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Division Found.
        /// </summary>
        internal static string LblNoDivisionFound {
            get {
                return ResourceManager.GetString("LblNoDivisionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Division.
        /// </summary>
        internal static string LblTotalDivision {
            get {
                return ResourceManager.GetString("LblTotalDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDivisionDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDivisionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division deleted successfully!.
        /// </summary>
        internal static string MsgDivisionDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDivisionDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division could not saved!.
        /// </summary>
        internal static string MsgDivisionSaveFailed {
            get {
                return ResourceManager.GetString("MsgDivisionSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division saved successfully!.
        /// </summary>
        internal static string MsgDivisionSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDivisionSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division could not updated!.
        /// </summary>
        internal static string MsgDivisionUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDivisionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division updated successfully!.
        /// </summary>
        internal static string MsgDivisionUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDivisionUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Division name found!.
        /// </summary>
        internal static string MsgDuplicateDivision {
            get {
                return ResourceManager.GetString("MsgDuplicateDivision", resourceCulture);
            }
        }
    }
}
