//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLeaveType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLeaveType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLeaveType", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Carry Forward?.
        /// </summary>
        internal static string LblCarryForward {
            get {
                return ResourceManager.GetString("LblCarryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string LblLeaveType {
            get {
                return ResourceManager.GetString("LblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Leave Type Found.
        /// </summary>
        internal static string LblNoLeaveTypeFound {
            get {
                return ResourceManager.GetString("LblNoLeaveTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Days.
        /// </summary>
        internal static string LblPayDays {
            get {
                return ResourceManager.GetString("LblPayDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string LblPaymentMode {
            get {
                return ResourceManager.GetString("LblPaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string LblShortName {
            get {
                return ResourceManager.GetString("LblShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Leave Type.
        /// </summary>
        internal static string LblTotalLeaveType {
            get {
                return ResourceManager.GetString("LblTotalLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same LeaveType name found!.
        /// </summary>
        internal static string MsgDuplicateLeaveType {
            get {
                return ResourceManager.GetString("MsgDuplicateLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType can&apos;t be deleted!.
        /// </summary>
        internal static string MsgLeaveTypeDeleteFailed {
            get {
                return ResourceManager.GetString("MsgLeaveTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType deleted successfully!.
        /// </summary>
        internal static string MsgLeaveTypeDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveTypeDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType could not saved!.
        /// </summary>
        internal static string MsgLeaveTypeSaveFailed {
            get {
                return ResourceManager.GetString("MsgLeaveTypeSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType saved successfully!.
        /// </summary>
        internal static string MsgLeaveTypeSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveTypeSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType could not updated!.
        /// </summary>
        internal static string MsgLeaveTypeUpdateFailed {
            get {
                return ResourceManager.GetString("MsgLeaveTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType updated successfully!.
        /// </summary>
        internal static string MsgLeaveTypeUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgLeaveTypeUpdateSuccessful", resourceCulture);
            }
        }
    }
}
