//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDutyShift {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDutyShift() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceDutyShift", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift.
        /// </summary>
        internal static string LblDutyShift {
            get {
                return ResourceManager.GetString("LblDutyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift Master.
        /// </summary>
        internal static string LblDutyShiftMaster {
            get {
                return ResourceManager.GetString("LblDutyShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Time.
        /// </summary>
        internal static string LblInTime {
            get {
                return ResourceManager.GetString("LblInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max In Time.
        /// </summary>
        internal static string LblMaxInTime {
            get {
                return ResourceManager.GetString("LblMaxInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Duty Shift Found.
        /// </summary>
        internal static string LblNoDutyShiftFound {
            get {
                return ResourceManager.GetString("LblNoDutyShiftFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Time.
        /// </summary>
        internal static string LblOutTime {
            get {
                return ResourceManager.GetString("LblOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string LblSchool {
            get {
                return ResourceManager.GetString("LblSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Duty Shift.
        /// </summary>
        internal static string LblSelectDutyShift {
            get {
                return ResourceManager.GetString("LblSelectDutyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string LblSlDutyShift {
            get {
                return ResourceManager.GetString("LblSlDutyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DutyShift.
        /// </summary>
        internal static string LblTotalDutyShift {
            get {
                return ResourceManager.GetString("LblTotalDutyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Duty Shiftname found!.
        /// </summary>
        internal static string MsgDuplicateDutyShift {
            get {
                return ResourceManager.GetString("MsgDuplicateDutyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift can&apos;t be deleted!.
        /// </summary>
        internal static string MsgDutyShiftDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift deleted successfully!.
        /// </summary>
        internal static string MsgDutyShiftDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift could not saved!.
        /// </summary>
        internal static string MsgDutyShiftSaveFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift saved successfully!.
        /// </summary>
        internal static string MsgDutyShiftSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift tcould not updated!.
        /// </summary>
        internal static string MsgDutyShiftUpdateFailed {
            get {
                return ResourceManager.GetString("MsgDutyShiftUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty Shift updated successfully!.
        /// </summary>
        internal static string MsgDutyShiftUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgDutyShiftUpdateSuccessful", resourceCulture);
            }
        }
    }
}
