//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSchool {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSchool() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceSchool", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LblAddress {
            get {
                return ResourceManager.GetString("LblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrict {
            get {
                return ResourceManager.GetString("LblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrictName {
            get {
                return ResourceManager.GetString("LblDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string LblDivision {
            get {
                return ResourceManager.GetString("LblDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divsion Name.
        /// </summary>
        internal static string LblDivisionName {
            get {
                return ResourceManager.GetString("LblDivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN.
        /// </summary>
        internal static string LblEIN {
            get {
                return ResourceManager.GetString("LblEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LblMobile {
            get {
                return ResourceManager.GetString("LblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No School Found.
        /// </summary>
        internal static string LblNoSchoolFound {
            get {
                return ResourceManager.GetString("LblNoSchoolFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string LblPhone {
            get {
                return ResourceManager.GetString("LblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string LblSchool {
            get {
                return ResourceManager.GetString("LblSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        internal static string LblSelectDistrict {
            get {
                return ResourceManager.GetString("LblSelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        internal static string LblSelectDivision {
            get {
                return ResourceManager.GetString("LblSelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School.
        /// </summary>
        internal static string LblSelectSchool {
            get {
                return ResourceManager.GetString("LblSelectSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Upazila.
        /// </summary>
        internal static string LblSelectUpazila {
            get {
                return ResourceManager.GetString("LblSelectUpazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total School.
        /// </summary>
        internal static string LblTotalSchool {
            get {
                return ResourceManager.GetString("LblTotalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila.
        /// </summary>
        internal static string LblUpazila {
            get {
                return ResourceManager.GetString("LblUpazila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upazila.
        /// </summary>
        internal static string LblUpazilaName {
            get {
                return ResourceManager.GetString("LblUpazilaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same School name found!.
        /// </summary>
        internal static string MsgDuplicateSchool {
            get {
                return ResourceManager.GetString("MsgDuplicateSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School can&apos;t be deleted!.
        /// </summary>
        internal static string MsgSchoolDeleteFailed {
            get {
                return ResourceManager.GetString("MsgSchoolDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School deleted successfully!.
        /// </summary>
        internal static string MsgSchoolDeleteSuccessful {
            get {
                return ResourceManager.GetString("MsgSchoolDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School could not saved!.
        /// </summary>
        internal static string MsgSchoolSaveFailed {
            get {
                return ResourceManager.GetString("MsgSchoolSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School saved successfully!.
        /// </summary>
        internal static string MsgSchoolSaveSuccessful {
            get {
                return ResourceManager.GetString("MsgSchoolSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School tcould not updated!.
        /// </summary>
        internal static string MsgSchoolUpdateFailed {
            get {
                return ResourceManager.GetString("MsgSchoolUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School updated successfully!.
        /// </summary>
        internal static string MsgSchoolUpdateSuccessful {
            get {
                return ResourceManager.GetString("MsgSchoolUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School search text here.
        /// </summary>
        internal static string TextBoxSearch_School {
            get {
                return ResourceManager.GetString("TextBoxSearch_School", resourceCulture);
            }
        }
    }
}
